//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.01 at 12:33:55 AM AEDT 
//


package au.gov.dva.digitize.document.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MailMeta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MailMeta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="envelopeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="docId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bagId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scanDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="archiveNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trimRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mailBox" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MailMeta", propOrder = {
    "envelopeId",
    "docId",
    "bagId",
    "scanDate",
    "fileName",
    "archiveNum",
    "trimRef",
    "mailBox"
})
public class MailMeta {

    @XmlElement(required = true)
    protected String envelopeId;
    @XmlElement(required = true)
    protected String docId;
    @XmlElement(required = true)
    protected String bagId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar scanDate;
    @XmlElement(required = true)
    protected String fileName;
    @XmlElement(required = true)
    protected String archiveNum;
    @XmlElement(required = true)
    protected String trimRef;
    @XmlElement(required = true)
    protected String mailBox;

    /**
     * Gets the value of the envelopeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvelopeId() {
        return envelopeId;
    }

    /**
     * Sets the value of the envelopeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvelopeId(String value) {
        this.envelopeId = value;
    }

    /**
     * Gets the value of the docId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocId() {
        return docId;
    }

    /**
     * Sets the value of the docId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocId(String value) {
        this.docId = value;
    }

    /**
     * Gets the value of the bagId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBagId() {
        return bagId;
    }

    /**
     * Sets the value of the bagId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBagId(String value) {
        this.bagId = value;
    }

    /**
     * Gets the value of the scanDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScanDate() {
        return scanDate;
    }

    /**
     * Sets the value of the scanDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScanDate(XMLGregorianCalendar value) {
        this.scanDate = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the archiveNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveNum() {
        return archiveNum;
    }

    /**
     * Sets the value of the archiveNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveNum(String value) {
        this.archiveNum = value;
    }

    /**
     * Gets the value of the trimRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrimRef() {
        return trimRef;
    }

    /**
     * Sets the value of the trimRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrimRef(String value) {
        this.trimRef = value;
    }

    /**
     * Gets the value of the mailBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailBox() {
        return mailBox;
    }

    /**
     * Sets the value of the mailBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailBox(String value) {
        this.mailBox = value;
    }

}
